### ISSUE TITLE
Not possible to update an existing issue?

### ISSUE THREAD

**Issue by endymion** [sumoheavy/jira-ruby#100]
I've spent about the last six hours trying to figure out how to use the JIRA API from Ruby, using this gem, to create, update, and comment on an issue in JIRA.  Simple, right?  NO.  This gem is so poorly documented that it took hours just to log into our JIRA account with it because the secret of using :context => '' is not mentioned anywhere and I had to figure it out myself.  Then I had to figure out how to find the IDs for projects and issue types by inspecting the HTML from atlassian.net and I was finally able to post an issue.

Updating an existing issue, however, is a complete mystery.  I'm guessing that it will be like the other issues: that it will work if I can find some sample code somewhere.  The sample code in the documentation for updating records absolutely does not work.  Now I'm just throwing things against the wall to see if anything sticks.  I seriously think that I would have been better off pulling out Capybara and writing a web bot to do this instead of trying to use this terrible API gem.

Here are a few examples of failed attempts to post an update to an existing issue.  I get a 400 response and no error messages in the issue's data structure.

```
client = JIRA::Client.new(options)
issue = client.Issue.find('ENG-23')
begin
  issue.save!(
      {
        'fields' =>
          {
            'description' => 'This story was posted by a bot.'
          }      
      }
    )
rescue JIRA::HTTPError => e
  puts e.response.code
  puts e.response.message
  puts e.response.body  
end 
```

Result:

```
$ bundle exec ruby jira.rb 
400
Bad Request
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

That mirrors the structure used to create that same issue, with the fields nested under 'fields'.  But obviously it doesn't work.  And it provides absolutely no hint about why it didn't work.

Another attempt:

```
client = JIRA::Client.new(options)
issue = client.Issue.find('ENG-23')
begin
  issue.save!(
      {
        'description' => 'This story was posted by a bot.'
      }
    )
rescue JIRA::HTTPError => e
  puts e.response.code
  puts e.response.message
  puts e.response.body  
end 
```

Result:

```
$ bundle exec ruby jira.rb 
400
Bad Request
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Another attempt:

```
client = JIRA::Client.new(options)
issue = client.Issue.find('ENG-23')
issue.set_attrs(
    {
      'fields'=>
        {
          'summary' => 'Hello, World!',
          'description' => 'This story was posted by a bot.',
          'project' => {'id' => 10207}, # ENG -- Engineering,
          'issuetype' => {'id' => 10206} # Story
        }
    }
  )
begin
  issue.save!({})
rescue JIRA::HTTPError => e
  puts e.response.code
  puts e.response.message
  puts e.response.body  
end 
```

Result:

```
$ bundle exec ruby jira.rb 
400
Bad Request
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Another attempt:

```
client = JIRA::Client.new(options)
issue = client.Issue.find('ENG-23')
begin
  issue.save!(
      {
        'fields'=>
          {
            'summary' => 'Hello, World!',
            'description' => 'This story was posted by a bot.',
            'project' => {'id' => 10207}, # ENG -- Engineering,
            'issuetype' => {'id' => 10206} # Story
          }
      }
    )
rescue JIRA::HTTPError => e
  puts e.response.code
  puts e.response.message
  puts e.response.body  
end 
```

Same result.

The real issue here is that I'm an idiot for wasting so much of my time on trying to make this work when it's obviously never going to work.  Is that correct?  Or can this gem actually update issues in JIRA?

If this gem can't update issues in JIRA then why is it wasting space on GitHub?

**Comment by endymion** [comment]
I should mention that I'm authenticating with HTTP Basic and that the API user has access to update the record, which I confirmed by logging in as that user and updating the record.

**Comment by andrewhavens** [comment]
@endymion I feel your pain. However, your disparaging comments are not productive. The maintainers of this gem volunteer their time to maintain a gem that someone else created, and are under no obligation to help you. I'm sure they don't appreciate your negative tone. If it's so bad, why don't you try using one of the [60 other JIRA gems](https://rubygems.org/search?page=1&query=jira&utf8=%E2%9C%93).

I realize it's not mentioned in the README, but there are two files in the repo which list a lot of examples, including updating issues. Perhaps you did not see these examples?
* [Examples using OAuth](https://github.com/sumoheavy/jira-ruby/blob/master/example.rb)
* [Examples using HTTP Basic](https://github.com/sumoheavy/jira-ruby/blob/master/http-basic-example.rb)

I agree, the readme needs some improvement. However, docs aren't a replacement for getting your hands dirty and reading through the source code.

**Comment by legkvla** [comment]
Good news, guys!
I have fixed it!

The issue was that sometimes url didn't have '/' prefix.

https://github.com/legkvla/jira-ruby/commits/master

https://github.com/legkvla/jira-ruby/commit/3508d06b92247f55f3b11b354b41eab3f725bc10

**Comment by legkvla** [comment]
Have created pull request for you, so you can better understand what's happened and how it could be fixed: https://github.com/sumoheavy/jira-ruby/pull/112

**Comment by omehegan** [comment]
https://github.com/sumoheavy/jira-ruby/pull/119 fixes this issue.

**Comment by scottyseus** [comment]
For what it's worth, I also noticed that the request was leaving the '/' off of the beginning of the URL (e.g. 'https:jira.example.comrest/api/2/blablabla' notice the lack of '/' between 'com' and 'rest'), and what fixed this for me was removing the '/' at the end of the host name I gave the Client object.

I changed
```ruby
client = JIRA::Client.new(
  username: username,
  password: password,
  site: 'https://jira.example.com/',
  context_path: '', 
  auth_type: :basic)
```
to

```ruby
client = JIRA::Client.new(
  username: username,
  password: password,
  site: 'https://jira.example.com',
  context_path: '', 
  auth_type: :basic)
```

**Comment by legkvla** [comment]
I found bug in my last fix I made last summer. Since issue is still open - I would like provide a pull request.
Also I found conditions when issue reproduced - for example, when you use Attlassian SDK and your jira instance installed not in root context but in /jira path instead.
If somebody experienced this issue - could you please test my PR too and confirm that it fixes issue. So we can close ticket.
