### ISSUE TITLE
JIRA 6.5: Saving Fields consistently throws a 400: Bad Request

### ISSUE THREAD

**Issue by intere** [sumoheavy/jira-ruby#105]
I have debugged this and found that the base.rb - url method (when hitting the if ``@attrs['self']`` case) was not utilizing the ``prefix`` and creating urls that did not start with a slash (``/``) prefix.  I'm going to issue a pull request to address this.

I have tested it and found it to work for Jira 6.5.  I would assume this will be a universal fix, though.

**Comment by legkvla** [comment]
Looks like #100 is duplicate of this issue.

**Comment by bobbrodie** [comment]
#100 Has been merged and closed - let's reopen this if necessary. Thanks!
