### ISSUE TITLE
New issue not getting saved, no error thrown.

### ISSUE THREAD

**Issue by srivatsag1** [sumoheavy/jira-ruby#109]
Issue created is saved only when:

@issue = @jira_client.Issue.build
 hash = {"fields"=>{ "summary"=>params["summary"],"project"=>{"id"=>"10000"},"issuetype"=>{"id"=>"3:}}}
@issue.save(hash)

Not when:

@issue = @jira_client.Issue.build
hash = {"fields"=>{ "summary"=>params["summary"],"project"=>{"id"=>"10000"},"issuetype"=>{"id"=>params["issuetype"]},"description"=>params["description"]}}
@issue.save(hash)

Can someone guide me why?

**Comment by crimsonknave** [comment]
I had the same issue. It appears to be caused by having a trailing / in your site option. The code below worked for me.

```ruby
options = { 
  username: username,
  password: password,
  site: 'https://jira.com',
  context_path: '',
  auth_type: :basic
}
```

**Comment by kjw1** [comment]
If you want it to throw an error, you should use `save!` instead of `save`. The plain version returns true/false.
