### ISSUE TITLE
Return total from jira search

### ISSUE THREAD

**Issue by dsjellz** [sumoheavy/jira-ruby#110]
I am trying to fetch all the issues from a specific filter.

``` ruby
@jira_client.Filter.find(12345).issues
```

But this only returns the actual 'issues' that come back from the jql. As far as I can tell, the Issue class drops any data outside of the 'issues' array: https://github.com/sumoheavy/jira-ruby/blob/master/lib/jira/resource/issue.rb#L41-43. This includes: expand, startAt, maxResults, and total. This is an example of the direct response from the JIRA api.

``` json
{
  "expand": "schema,names",
  "startAt": 0,
  "maxResults": 50,
  "total": 244,
  "issues":[...],
}
```

The only workarounds I could come up with are:
**manually execute the request to get this value**

``` ruby
jql = @jira_client.Filter.find(12345).jql
JSON.parse(@jira_client.get("https://jira.yourdomain.com/rest/api/2/search?jql=#{URI.escape(jql)}").body)['total']
```

or

**Continue to pull until the page size is less than the max_results size**

``` ruby
jql = @jira_client.Filter.find(12345).jql
aggregate_issues = []
max_results = 50
loop do
  issues = JIRA::Resource::Issue.jql(@jira_client, jql, max_results: max_results, start_at: aggregate_issues.size)
  aggregate_issues.concat issues
  break if issues.size < max_results
end
```

Am I missing something? Or are these the only options for handling this?

**Comment by slaith** [comment]
I have the same issue. There seems no way of getting the total size

**Comment by dugjason** [comment]
So the issue here appears to be that a `JIRA::Resource::Issue.jql(...)` call returns an array containing `JIRA::Resource::Issue` objects. Other implementations return something like a `ResourceArray` object, which contains the array of resources + any metadata.

**Comment by camdenbrown** [comment]
I ended up manually executing the request like above. Thanks for the workaround.

**Comment by rompic** [comment]
i stumbled upon this and it was implemented in https://github.com/sumoheavy/jira-ruby/pull/167
