### ISSUE TITLE
How I can create a log work entry ?

### ISSUE THREAD

**Issue by bolom** [sumoheavy/jira-ruby#120]
Hi

I am trying to create to log work for a specific issue. I have tried that

projects = client.Project.all
issue = client.Issue.find("13921")
w = issue.worklogs.build
 w.timeSpentSeconds = "12000" 

However i have got this error

`method_missing': undefined method `timeSpentSeconds=' for #<JIRA::Resource::Worklog:0x007f831db3f360> (NoMethodError)
	from jira.rb:33:in `<main>'

Thanks for any help

**Comment by diwaniuk** [comment]
Hi Bolo,

try this way:

```ruby
w = issue.worklogs.build
w.save!("timeSpentSeconds" => "10403")
```

-
Daniel
