### ISSUE TITLE
Deleting the last comment returns 400 error

### ISSUE THREAD

**Issue by SDarayan** [sumoheavy/jira-ruby#127]
My program executes the following commands.

    client = JIRA::Client.new({
        :username => username,                                                                                                                                                     
        :password => password,
        :site     => site,
        :context_path => '',
        :auth_type => :basic,
        :use_ssl => true,
    })
    issue = client.Issue.find(id)
    issue.comments.last.delete`

I realize that the last command is the failure since my program can get JIRA issues and print them out.
The following error is returned.

    400
    Bad Request
    <html>
    <head><title>400 Bad Request</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>

My question is, why the error?

**Comment by bobbrodie** [comment]
@SDarayan I'm not getting an error when deleting the last comment on an issue. Can you provide a more specific use case? Without the full context, I can provide a few pieces of information that may or may not be helpful:

* Your options are defined, correct? (username, password, site, id)
* If you're using JIRA Cloud, you're using https:// in your site variable
* The id variable is a valid ticket number, correct?
* Does your user have permission to delete that comment? On our instance for example, users can only delete their own comments, and administrators can delete comments belonging to other users.

I've tested this on our live JIRA instance and didn't have any trouble, but feel free to reach out to me over email at robert@sumoheavy.com

**Comment by SDarayan** [comment]
Actually, I am closing this one out. The issue was with the trailing slash on the Jira URL.
