### ISSUE TITLE
Example for JQL has syntax error

### ISSUE THREAD

**Issue by slava-vishnyakov** [sumoheavy/jira-ruby#130]
Example for JQL has syntax error

https://github.com/sumoheavy/jira-ruby/blob/master/http-basic-example.rb#L54

```
# client.Issue.jql('PROJECT = "SAMPLEPROJECT"', [comments, summary]).each do |issue|
```

methods `comments` and `summary` are not defined.

It should be:

```
client.Issue.jql('PROJECT = "SAMPLEPROJECT"', {fields: %w(summary status)}).each do |issue|
```

**Comment by bobbrodie** [comment]
@slava-vishnyakov that file could definitely use some love. Those were added a loonnnnnng time ago (I think before we inherited it) and are commented out. This will definitely get into the mix.

**Comment by slava-vishnyakov** [comment]
Thanks!
