### ISSUE TITLE
update issue status

### ISSUE THREAD

**Issue by diwaniuk** [sumoheavy/jira-ruby#133]
Hi, 
is there a way to change issue state? I'm trying do this by update but unfortunately it doesn't work. 

<code>issue.save({"update"=>{"comment"=>[{"add"=>{"body"=>"Comment added when resolving issue"}}]},"transition"=>{"id"=>"2"}})</code>

Thanks for any advice.
Daniel.

**Comment by diwaniuk** [comment]
The problem is solved. Finally i found that I'm using wrong method, correct is transitions.

<code>
trans = issue.transitions.build
trans!("transition" => {"id" => "2"})
</code>

**Comment by pac78275** [comment]
Doesn't seem to work for me. I get the following error:
```
irb(main):061:0> issue.transitions.build.save!('transition' => {'id' => '4'})
JIRA::HTTPError: JIRA::HTTPError
        from /Users/jwestmor/.rvm/gems/ruby-2.3.3/gems/jira-ruby-1.1.3/lib/jira/request_client.rb:16:in `request'
        from /Users/jwestmor/.rvm/gems/ruby-2.3.3/gems/jira-ruby-1.1.3/lib/jira/client.rb:213:in `request'
        from /Users/jwestmor/.rvm/gems/ruby-2.3.3/gems/jira-ruby-1.1.3/lib/jira/client.rb:201:in `post'
        from /Users/jwestmor/.rvm/gems/ruby-2.3.3/gems/jira-ruby-1.1.3/lib/jira/base.rb:351:in `save!'
        from (irb):61
        from /Users/jwestmor/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'
```

**Comment by arincon9** [comment]
@pac78275 Were you every able to resolve `JIRA::HTTPError`? I am having the same issue.

**Comment by ahusseini** [comment]
@arincon9 I'm new to ruby so I can't explain this too well. I was getting Bad Request response despite the transition working, after switch to `save` instead of `save!` it no longer returned a Bad Request.

**Comment by guilpejon** [comment]
Does anybody knows how to fix this? I'm getting the same error as @pac78275 and @arincon9

**Comment by guilpejon** [comment]
Found the issue. JIRA throws a `JIRA::HTTPError` when you try to transition to an invalid ID. Make sure you can transition the issue to that specific ID before trying to transition. Found the solution here: https://stackoverflow.com/a/23297391/3012906
