### ISSUE TITLE
Is there a way to link a ticket to an Epic with this gem?

### ISSUE THREAD

**Issue by agargiulo** [sumoheavy/jira-ruby#166]
I thought it would be by using `client.Issuelink.build` but I can't see what issue type would work to link a ticket into an Epic because I'm fairly certain it's not an `Issuelink`

**Comment by agargiulo** [comment]
ignore this, I figured it out with customfield things

**Comment by zeeshangulzar** [comment]
@agargiulo  Please if you can share your solution. I also need to add a task in specific epic.

**Comment by agargiulo** [comment]
I'm so sorry, I can't remember and I don't have the code anymore. If I remember, I'll update this.
