### ISSUE TITLE
jura-ruby in a Rails application give cannot find file 'lira' error

### ISSUE THREAD

**Issue by jjwright55** [sumoheavy/jira-ruby#170]
I have a simple spec test that just does a JIRA::Client.new(@options) on a Rails project and I get that require cannot load the file 'jira' in active support. I wrote a simple test program, outside of rails, and it works ok. My Gemfile has
gem 'jira-ruby', :require => 'jira-ruby'

Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- jira (LoadError)
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/jira-ruby-1.0.0/lib/jira/railtie.rb:1:in `<top (required)>'
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/jwright/.rvm/gems/ruby-2.1.5@order-processor/gems/jira-ruby-1.0.0/lib/jira-ruby.rb:43:in `<top (required)>'
	from /Users/

**Comment by jjwright55** [comment]
Changed gem 'jira-ruby', :require => 'jira_ruby'
to
gem 'jira-ruby', :require => false
and it worked.

**Comment by bobbrodie** [comment]
@jjwright55 this changed once we hit 1.0.0 since it was not a backwards-compatible change. I apologize for the inconvenience!

**Comment by a-leung** [comment]
just wondering, what's the recommended way to include `jira-ruby` in the Gemfile for rails? the way @jjwright55 described:

`'jira-ruby', require: false`

?

thanks
