### ISSUE TITLE
How to page through issues for a given project

### ISSUE THREAD

**Issue by NeedaMehmud** [sumoheavy/jira-ruby#196]
How do I loop through all of the issues for a given project? Say I am doing something like this:

```ruby
project = client.Project.find('SAMPLEPROJECT')

project.issues.each do |issue|
 puts "#{issue.id} - #{issue.summary}"
end
```

```project.issues``` returns only the first 50 and I'm unsure how to get the next 50 and so on.

**Comment by uchagani** [comment]
@NeedaMehmud You can pass in parameters to the issues method like so:

```ruby
 project.issues({startAt:1, maxResults:100})
```

Using the above you can loop through and set your ```startAt``` value at the previous loops stop amount + 1 and keep looping until you've looped through all of the issues.  Something like:

```ruby
  loop do
    start_at = 1 if start_at.nil?
    project.issues(startAt: start_at).each do |issue|
      puts "#{issue.id} - #{issue.summary}" 
    end
    break if project.issues.count == 0
    start_at = start_add + project.issues.count
  end
```

There may be a smarter way to do the loop if there is a method to find the total count of issues in a project.  I'd have to dig through the code to see if there is.

**Comment by NeedaMehmud** [comment]
@uchagani Thank you for your help!

**Comment by bobbrodie** [comment]
Hey @uchagani thanks for jumping in here - it makes me so happy to see folks working together. Since this solved @NeedaMehmud's issue, I'll close this out.
