### ISSUE TITLE
Unable to join slack channel

### ISSUE THREAD

**Issue by uchagani** [sumoheavy/jira-ruby#197]
Getting the following error when trying to sign up:

```
This team's administrator has not enabled email signups.

Sign up for jira-ruby.slack.com

Ask your administrator to send you an invitation.
```

**Comment by SimonMiaou** [comment]
I would also like to join the slack channel

**Comment by bobbrodie** [comment]
Hey guys, I'll close this out since we now have https://jira-ruby-slackin.herokuapp.com. Thanks!
