### ISSUE TITLE
Could you write changelog or release note?

### ISSUE THREAD

**Issue by keepcosmos** [sumoheavy/jira-ruby#209]
If I can follow up any change of each gems, It will be very helpful. :)

**Comment by avand** [comment]
I'm looking to upgrade a project that's on `0.1.14` of this gem to latest version. I'm just noticing there is no CHANGELOG so I'm kind of on my own. Any major gotchas you could clue me into?

🙏

**Comment by animista01** [comment]
+1 I think it's needed.

**Comment by smridge** [comment]
Given this issue opened in 2017, what are the chances for a Changelog?

**Comment by SimonMiaou** [comment]
I think it might be hard to get one person keeping it up to date.
At least for me that don't work with Jira ATM, I do my best to keep the gem maintain but hardly find time to bring more.

What do you think about you create a PR introducing a changelog with minimal guidelines and we try to enforce contributors to keep it up to date when submitting a PR?

**Comment by bobbrodie** [comment]
Hey everyone,

I'm getting back into this gem, and will be starting a semver-based changelog starting with version 3.0.0. We are dropping support for EOL Ruby and adding support for new versions, along with updated testing and new features.

Thanks!
