### ISSUE TITLE
Getting error message is not obvious

### ISSUE THREAD

**Issue by Karamorf** [sumoheavy/jira-ruby#210]
How do I get the error response from Jira out of the jira-ruby object? For example, if I'm trying to create an issue:
issue = jira.Issue.build
issue.save({_data_})
issue.fetch
>>>>>>>>> Exception response: {"errorMessages":[],"errors":{"project":"Could not find project by id or key."}}

How can I then get that error message out of the issue object?

**Comment by Karamorf** [comment]
Okay, I've figured this all out and it's ridiculous. Let's start with one assumption:
If my interaction with Jira fails for any reason, I'm probably going to want whatever Jira said was wrong.

Going from there, lets walk through what this gem goes in such a case. First off, here you print the message I care about the most:
https://github.com/sumoheavy/jira-ruby/blob/a1eb8e9692508e53bbe8214f626d0701086112c9/lib/jira/base.rb#L367

That's great, but who are you to decide that I want stuff going to stdout. That's a lot of assumptions. But okay, whatever. I then had to try and walk through all of this to finally figure out that the error message I want is actually in issue.attrs. Fine great, I can move on with life but why on earth would I ever expect it to find it their?

You go to the length to make a has_error method, but not a method to get the error?

Then the gem still throws an exception in this case ("JIRA::HTTPError") which does not have the error message I care about in it. It then has things like "Method Not Allowed" in it and whatever else. Maybe that's the http response? It's just so meaningless to the context of "create issue" in the work flow I'm trying to do. Why even have this thrown up? If anything, I want you to rethrow the exception that has the actual message I would care about.

If I continue poking at the exception you do throw, it has a "response" object in it that yet again has more worthless information in it.

I get wanting to put the error message into the original issue object, that makes sense. But the way you've decided to go about it is just all sorts of annoying and convoluted.

In the end, the real reason this is a problem at all is because:
* there is no documentation for handling an error from Jira
* it's not obvious that the error goes into the "attrs" method

**Comment by bobbrodie** [comment]
@Karamorf thanks for the abundance of information and thought. For what it's worth, this gem was on the verge of being thrown away, and we asked to take over the repo so it wouldn't be because nobody else wanted to. We're working on building a community about it. If you have ideas, we would love for you to contribute what you feel would be better solutions! We also encourage you to sign up for our Slack instance here https://jira-ruby-slackin.herokuapp.com. Building a community for an obscure gem is not easy, and requires us to all funnel frustration into creative collaboration.

**Comment by SimonMiaou** [comment]
I will close this issue as it is solved
