### ISSUE TITLE
feature request:  jira 7.x api compatibility

### ISSUE THREAD

**Issue by rlyons** [sumoheavy/jira-ruby#217]
We will be moving to 7.2.7 in 3 weeks, and I need to make calls that work with the new rest structure.
 
I can rewrite everything to use bare rest, but I thought I would make a request to get a version of this library that would work as a drop-in replacement.

**Comment by rlyons** [comment]
For instance, when I do client.Issue.jql
JIRA::HTTPError: JIRA::HTTPError
       request at /REDACTED/.gem/jruby/2.3.0/gems/jira-ruby-1.2.0/lib/jira/request_client.rb:16
       request at /REDACTED/.gem/jruby/2.3.0/gems/jira-ruby-1.2.0/lib/jira/client.rb:213
           get at /REDACTED/.gem/jruby/2.3.0/gems/jira-ruby-1.2.0/lib/jira/client.rb:191
           jql at /REDACTED/.gem/jruby/2.3.0/gems/jira-ruby-1.2.0/lib/jira/resource/issue.rb:64
  block in jql at /REDACTED/.gem/jruby/2.3.0/gems/jira-ruby-1.2.0/lib/jira/base_factory.rb:33

**Comment by SimonMiaou** [comment]
@rlyons Could you provide the content of the exception?
