### ISSUE TITLE
Suggestion for some improvements to cookie based authentication

### ISSUE THREAD

**Issue by trapeze-bell-peter** [sumoheavy/jira-ruby#238]
I want to use cookie based authentication as part of my login process.  As such I want to create a per user JIRA::Client.  I have two suggestions for improvements to jira-ruby's cookie based authentication.

Suggestion 1: at the moment if the cookie authorisation fails due to an incorrect username/password when creating the JIRA::Client, there is no easy way to establish this has happened.  I would like to suggest that we add an instance method to `JIRA::Client` called `authorised?`.  For basic authorisation, it would be set once we have a successful API call.  For Cookie and OAuth2 it would be set if the authorisation succeeded.

Suggestion 2: My reading of the Altassian documentation is that once we have a cookie, we don't need to include the user and password in subsequent API calls.  At the moment, we still store username and password after the initial authorisation and resubmit this information on each subsequent API call.  I would like not to store the username and password once we have received the authorisation cookie.  That way, we hold username and password for the minimum amount of time which obviously improves security.

If these suggestions are acceptable, happy to implement and submit a PR.

**Comment by SimonMiaou** [comment]
Looks good to me

**Comment by SimonMiaou** [comment]
Was implemented in #239
