### ISSUE TITLE
403 Forbidden for updates

### ISSUE THREAD

**Issue by lehresman** [sumoheavy/jira-ruby#240]
I am using the cloud-based JIRA, and my `JIRA::Client` options are:

```
options = {
	:private_key_file => "jira_privatekey.pem",
	:context_path     => '',
	:consumer_key     => CONSUMER_KEY,
	:site             => 'https://mysite.atlassian.net:443/'
}
```

My problem is that all updates are getting a 403 Forbidden response (yes, my user has the right permissions).

Digging into this gem a bit, I discovered that the problem lies here:
https://github.com/sumoheavy/jira-ruby/blob/master/lib/jira/base.rb#L448-L452
and here:
https://github.com/sumoheavy/jira-ruby/blob/master/lib/jira/base.rb#L430-L433

When I monkey-patch this and remove the "/" prefix, it works great.

Why is the "/" prefix hard coded here?  Seems like it's not really needed.  
Is there an elegant way to remove it?
Would you accept a PR that adds an option to remove it?

**Comment by lehresman** [comment]
This patch fixes the problem for me.  Would you be open to a PR with this solution?

```diff
diff --git a/lib/jira/base.rb b/lib/jira/base.rb
index 9df18d8..52f20c7 100644
--- a/lib/jira/base.rb
+++ b/lib/jira/base.rb
@@ -420,6 +420,10 @@ module JIRA
       respond_to?('errors')
     end
 
+    def needs_slash?(url)
+      url.match(/^https?:\/\//) ?  false : true
+    end
+
     def url
       prefix = '/'
       unless self.class.belongs_to_relationships.empty?
@@ -429,7 +433,7 @@ module JIRA
       end
       if @attrs['self']
         the_url = @attrs['self'].sub(@client.options[:site],'')
-        the_url = "/#{the_url}" if (the_url =~ /^\//).nil?
+        the_url = "/#{the_url}" if (the_url =~ /^\//).nil? && needs_slash?(the_url)
         the_url
       elsif key_value
         self.class.singular_path(client, key_value.to_s, prefix)
@@ -447,7 +451,7 @@ module JIRA
     # [07/Jun/2015:15:17:18 +0400] "PUT /jira/rest/api/2/issue/10111 HTTP/1.1" 204 -
     def patched_url
       result = url
-      return result if result.start_with?('/')
+      return result if result.start_with?('/') || !needs_slash?(result)
       "/#{result}"
     end
 ```

**Comment by SimonMiaou** [comment]
What about simply removing the extra slash from the site attribute?

```ruby
# before
:site             => 'https://mysite.atlassian.net:443/'

# after
:site             => 'https://mysite.atlassian.net:443'
```

Also, I don't see how your code is working

```ruby
    def needs_slash?(url)
      return !result.start_with?('/') && !url.match(/^https?:\/\//)
    end
```

Where does come `result` from? Why try to find https in the path? 🤔

**Comment by lehresman** [comment]
`result` was a bug that I discovered after I made this comment.

However, your solution of removing the slash from the end of the site attribute worked.  Wow, that was an easy solution.  Thanks.
