### ISSUE TITLE
Jira issue delete is not working.

### ISSUE THREAD

**Issue by bitxpert** [sumoheavy/jira-ruby#252]
Hey! I am trying to delete an issue from JIRA but it is giving JIRA:HTTP error.
What I am doing is:

jira_client = get_jira_client()
issue = jira_client.Issue.find(jira_issue_id)
issue.delete

Issue is being fetched successfully but `issue.delete` is throwing error.

**Comment by SimonMiaou** [comment]
Do you have any more data? What is the `response` of the exception?
You could also make sure you have the rights to delete the issue

**Comment by bitxpert** [comment]
It was permission's issue. Its working now. Thanks
