### ISSUE TITLE
Users list

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [sumoheavy/jira-ruby#260]
How can I list all users as an admin?

`users = client.User.find('.')`

leads to

```
Uncaught exception: JIRA::HTTPError
	/usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/jira-ruby-1.4.3/lib/jira/request_client.rb:16:in `request'
	/usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/jira-ruby-1.4.3/lib/jira/client.rb:220:in `request'
	/usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/jira-ruby-1.4.3/lib/jira/client.rb:198:in `get'
	/usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/jira-ruby-1.4.3/lib/jira/base.rb:339:in `fetch'
	/usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/jira-ruby-1.4.3/lib/jira/base.rb:110:in `find'
	/usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/jira-ruby-1.4.3/lib/jira/base_factory.rb:33:in `block (2 levels) in delegate_to_target_class'
```

**Comment by benzittlau** [comment]
I'm also encountering this same issue.  Listing users from a project is for some reason hard-coded to only return assignable users, and the bulk operations on the users endpoint that are available in the API appear to be unimplemented in this library.

**Comment by SimonMiaou** [comment]
Hi @Ilya-Kuchaev 
`client.User.find('.')` will not work as find is not build to retrieve lists, you should use `client.User.all`

@benzittlau If this is hardcoded, it is from the API or Jira as I didn't find anything in the sources. Or did I miss something?

**Comment by javierg** [comment]
This thread on Jira Comunity talks about using `+` instead of `_` on Jira Cloud. I tested and It worked as expected.

Not sure if `_` will work on the self-hosted version of Jira. If so, the wildcard should be dynamic.

```
diff --git a/lib/jira/resource/user.rb b/lib/jira/resource/user.rb
index 1529628..a211853 100644
--- a/lib/jira/resource/user.rb
+++ b/lib/jira/resource/user.rb
@@ -18,7 +18,7 @@ module JIRA
 
       # Cannot retrieve more than 1,000 users through the api, please see: https://jira.atlassian.com/browse/JRASERVER-65089
       def self.all(client)
-        response  = client.get("/rest/api/2/user/search?username=_&maxResults=#{MAX_RESULTS}")
+        response  = client.get("/rest/api/2/user/search?username=+&maxResults=#{MAX_RESULTS}")
         all_users = JSON.parse(response.body)
 
         all_users.flatten.uniq.map do |user|
```

**Comment by brissenden** [comment]
Just tested and `client.User.all` returns an empty array for self-hosted version.

**Comment by SimonMiaou** [comment]
I'm releasing #376 in a few minutes. It will impact the fetching of users so please try with it.

If there is any issue left after the update, please open a new issue stating your problem as I feel this one has more than one problem and I'd like to try cleanup a bit the outstanding issues of the gem
