### ISSUE TITLE
Basic auth with password to be deprecated - start using API tokens

### ISSUE THREAD

**Issue by mansilladev** [sumoheavy/jira-ruby#280]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), support for passwords in HTTP basic auth requests will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by jdanielian** [comment]
It seems like there is no code change required to support this. You can just supply the generated API token as the password, and it should still work. Maybe close this issue, so it doesn't appear the library needs an enhancement to keep working?

**Comment by kairos0ne** [comment]
Would be nice if you could update the docs to show that as most people will think you gem is not supported anymore.

**Comment by kairos0ne** [comment]
I get a Unauthorized (401) for JIRA::HTTPError with the API token as password. I've tested their Rest API with this also it doesn't allow the API token as password. I've included the context_path as empty string as others have suggested and this doesn't work. Ensured that I was using https etc... I'm afraid your gem doesn't appear to work as described in the basic auth example.  
`      def get_jira_client

        # add any extra configuration options for your instance of JIRA,
        # e.g. :use_ssl, :ssl_verify_mode, :context_path, :site
        options = {
          :user => 'Scott',
          :password => ENV['API_KEY'],
          :site => 'http://monochrome-development.atlassian.net:443/',
          :context_path => '',
          :auth_type => :basic,
        }
    
        @jira_client = JIRA::Client.new(options)
    
        # Add AccessToken if authorised previously.
        if session[:jira_auth]
          @jira_client.set_access_token(
            session[:jira_auth]['access_token'],
            session[:jira_auth]['access_key']
          )
        end
      end`

**Comment by rmf34** [comment]
pushed a basic readme update, can go deeper if desired
