### ISSUE TITLE
Project.find('non-existing-project') raises HTTP error

### ISSUE THREAD

**Issue by kali-hernandez** [sumoheavy/jira-ruby#293]
Trying to use `find` method for Project class, with a non existing project name, will raise an HTTPError rather than an empty result set:

```
[:get, "/rest/api/2/project/NONEXIST", nil, {"Accept"=>"application/json"}]
#<Net::HTTPNotFound 404  readbody=true>
/Library/Ruby/Gems/2.3.0/gems/jira-ruby-1.5.0/lib/jira/request_client.rb:18:in `request': JIRA::HTTPError
```

The code on `request_client.rb` seems to be doing this on purpose:
https://github.com/sumoheavy/jira-ruby/blob/master/lib/jira/request_client.rb#L16

When manually requesting the url above in the browser, I'm getting a 404 http status code but with a json response including a descriptive message:
`HTTP/2.0 404 Not Found`
```
{"errorMessages":["No project could be found with key 'NONEXIST'."],"errors":{}}
```
Seems to me like the API is purposely returning http 404 code for meaning that a project is not found, while the `request_client.rb` code is treating such 404 as an HTTP error when it isn't. The reply json should be equally parsed and passed back to the `Project.find` method which in turn should probably return an empty list.

**Comment by rmf34** [comment]
I started work on some more transparent error handling for this project over the weekend. Will push up and mention this and other issues when I have something working and tests passing.

**Comment by bobbrodie** [comment]
Hey everyone, I know it's been a while but I am commenting on old issues while closing them out. The latest version in master, soon to be released, attaches the error message in the `HTTPError`.

I've written about this here: https://github.com/sumoheavy/jira-ruby/issues/432#issuecomment-2078599003.

When I request a project that doesn't exist, I am receiving an HTTPError as expected and if you inspect the HTTPError with something like this:

```ruby
begin
  client.Project.find('NOEXIST')
rescue => e
  puts JSON.parse(e.response.body.inspect)
end
```

Then you'll see:

```json
{"errorMessages":["No project could be found with key 'NOEXIST'."],"errors":{}}
```
