### ISSUE TITLE
How to upgrade to TLSv1.2 

### ISSUE THREAD

**Issue by sonnguyen-logigear** [sumoheavy/jira-ruby#307]
As this [article](https://community.atlassian.com/t5/Jira-articles/Deprecating-TLSv1-and-TLSv1-1-for-Atlassian-Cloud-Products/ba-p/857357?utm_source=alert-email&utm_medium=email&utm_campaign=tlsv1-tlsv11-disabled_Eml-3846&jobid=103722165&subid=1137715151), we need to upgrade to TLSv1.2
Any config or idea to do this?
Thanks!

**Comment by sergio-bobillier** [comment]
Recently I have stumbled upon this issue. Apparently, some JIRA Cloud servers will not allow connections unless they are made with TLSv1.2 When anything else is used the server will simply close the connection:

```
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A.
```

It would be great if the SSL version could be specified, just as the SSL Verification. Right now is possible to do this:

```ruby
@jira_client ||= ::JIRA::Client.new(
  ...
  ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE
  ...
)
```

It would be possible to add another option to specify the SSL Version:

```ruby
@jira_client ||= ::JIRA::Client.new(
  ...
  ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE
  ssl_version: :TLSv1_2
  ...
)
```

This should be easy to implement as it is just a matter of setting the version in the Net::HTTP instance.
