### ISSUE TITLE
Net::HTTP::Proxy method is obsolete, should be replaced with Net::HTTP::New

### ISSUE THREAD

**Issue by kilunov** [sumoheavy/jira-ruby#344]
This was discovered when using a proxy server while setting no_proxy variables and noticed that all calls were still being sent out to the proxy server:
https://github.com/sumoheavy/jira-ruby/blob/master/lib/jira/http_client.rb#L44-L49

According to the docs, this Net:HTTP::Proxy method is now obsolete: https://apidock.com/ruby/Net/HTTP/Proxy/class

It's recommended to use the Net:HTTP:New method instead which would then pick up any ENV variables: https://apidock.com/ruby/Net/HTTP/new/class

**Comment by marlinpierce** [comment]
@SimonMiaou  Fixed in PR #419

**Comment by bobbrodie** [comment]
Issue #419 has been merged, so I'm going to close this out. Thanks, everyone!
