### ISSUE TITLE
Getting 400 error whenever I try to add a label to an issue

### ISSUE THREAD

**Issue by wpnzach** [sumoheavy/jira-ruby#348]
"exception"=>
    {"class"=>"Net::HTTPBadRequest", "code"=>"400", "message"=>"Bad Request"}}

Every time I try to execute this:

            labels = ['label1']
            client = JIRA::Client.new(options)
            issue = client.Issue.find(@issuekey)
            issue.save({"fields"=>{"labels"=>labels}})

Is there a different way I should be going about adding/removing labels from an issue?

**Comment by zhangyonguu** [comment]
@wpnzach 
Nice to see your problem solved. I'd like to share my experience.

I have encountered this kind of problem once, and finally found that the labels can not contain `space`, such as `my label`, it is not allowed, you must remove the `space` between `my` and `label`.
