### ISSUE TITLE
Fetch required field for a project and issuetype combination ?

### ISSUE THREAD

**Issue by AbhishekSharma20** [sumoheavy/jira-ruby#349]
Is there a way to fetch mandatory/required fields for a given combo of project and issuetype. from API I can go to <hostname>/rest/api/2/issue/createmeta?projectIds=<pid>&issuetypeIds=<it_id>&expand=projects.issuetypes.fields , and fetch all the fields where "required" is true. I just don't know how to do this through this gem.

**Comment by SimonMiaou** [comment]
You can use the `Createmeta` resource https://github.com/sumoheavy/jira-ruby/blob/master/lib/jira/resource/createmeta.rb

```ruby
client = JIRA::Client.new(options)
client. Createmeta.all
```
