### ISSUE TITLE
How to check if the jira ticket is having a file attachment using this jira-ruby api

### ISSUE THREAD

**Issue by gyancoupa** [sumoheavy/jira-ruby#395]
I am trying to automate Jira workflows and was wondering how to check if the jira ticket is having a file attachment using this jira-ruby api.
I tried the relevant code in the example.rb

`# # Add attachment to Issue
# # ------------------------
#  issue = client.Issue.find('PROJ-1')
#  attachment = issue.attachments.build
#  attachment.save('file': '/path/to/file')
#`

But this does not help to check if the attachment already exists or not

**Comment by marlinpierce** [comment]
If your issue is "MY-ISSUE" then you can get the issue object and it will have an {{attachments}} method with the collection of attachments.  You need to list {{"attachment"}} in the list of fields because Jira does no serve the attachments in this result by default.

    issue =  JIRA::Resource::Issue.find(client, 'MY-ISSUE', { fields: 'attachment' } )
    issue.attachments.find{ |attachment| ... }
