### ISSUE TITLE
Document how you get the list of the custom field names

### ISSUE THREAD

**Issue by drewish** [sumoheavy/jira-ruby#397]
I was trying to figure out what field names to use for some custom fields. It took me a while to figure out that `map_fields` returns the results. 

It might be nice put put an example like this into the docs:

Print out the full mapping of simplified labels to field names:
```rb
client = JIRA::Client.new(JIRA_AUTH)
puts client.Field.map_fields
```
Gives something like:
```
{"Parent"=>"parent", "Status_Category"=>"statusCategory", 
[...]
, "Created_At"=>"customfield_10088", "Slack_Link"=>"customfield_10089"}
```

**Comment by bobbrodie** [comment]
Hey @drewish I know it's been a while but I'm updating and preparing for version 3.0.0. Thanks for this, it's been added to https://github.com/sumoheavy/jira-ruby/wiki/Issues.
