### ISSUE TITLE
Upgrade oauth runtime dependency to 1.0.x

### ISSUE THREAD

**Issue by yadwinder11** [sumoheavy/jira-ruby#403]
## Description
While installing the `jira-ruby` gem, getting the following warning due to the [runtime dependency](https://github.com/sumoheavy/jira-ruby/blob/master/jira-ruby.gemspec#LL25C41-L25C44) `oauth` being on v0.x

>
<img width="936" alt="Screenshot 2023-03-07 at 11 29 56 AM" src="https://user-images.githubusercontent.com/79168430/223538096-f188bb31-169c-448b-a614-7a9b90596f82.png">

Are there any plans to move the `oauth` dependency to 1.0.x version soon?

**Comment by marlinpierce** [comment]
If I were to work on this issue in December and early January what standards do I need to meet for contribution of a merge request?

**Comment by marlinpierce** [comment]
I see this is handled in [PR 407](https://github.com/sumoheavy/jira-ruby/pull/407).

**Comment by bobbrodie** [comment]
Updated as part of #407

**Comment by bobbrodie** [comment]
This is in master now so I'll go ahead and close. Thank you so much!
