### ISSUE TITLE
Add new Ruby versions to the CI

### ISSUE THREAD

**Issue by Nicolasvb23** [sumoheavy/jira-ruby#408]
Hello,

I'm going to use this gem for Ruby 3.1, and I verified that the specs run properly there, so I was wondering if is possible to consider adding it to the CI 🙂

**Comment by Nicolasvb23** [comment]
**Update**
I created a PR for this, see the changes here:
https://github.com/sumoheavy/jira-ruby/pull/410

**Comment by bobbrodie** [comment]
Thank you so much!
