### ISSUE TITLE
Cannot add attachment to an issue when using default headers

### ISSUE THREAD

**Issue by marlinpierce** [sumoheavy/jira-ruby#416]
The 'Attachment#save!' method looks like it should add an attachment to an issue.
However, it was not passing the default headers for a multipart post.
Since we use a header to pass the Jira OAuth Access Token authorization the call would fail because of permissions.

Please see the fix in this Pull Request:

https://github.com/sumoheavy/jira-ruby/pull/415

**Comment by bobbrodie** [comment]
This is in master now so I'll go ahead and close. Thank you so much!
