### ISSUE TITLE
require 'jira' /  API Gem in a command line application broken

### ISSUE THREAD

**Issue by scottleedavis** [sumoheavy/jira-ruby#67]
I cannot require the 'jira' gem in ruby 1.9.3-p484.  In either a OSX or Win7 environment, both with same version of ruby.  Please fix!  Would really like to use this gem.

Here is the error.

irb(main):001:0> require 'pp'
=> true
irb(main):002:0> require 'jira'
/Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/jira-0.1.0/lib/jira/cli.rb:28: warning: else without rescue is useless
SyntaxError: /Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/jira-0.1.0/lib/jira/cli.rb:24: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n'
/Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/jira-0.1.0/lib/jira/cli.rb:65: syntax error, unexpected keyword_end, expecting $end
    from /Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/jira-0.1.0/lib/jira.rb:5:in `<top (required)>'
    from /Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in`require'
    from /Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /Users/daviss/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in`require'
    from (irb):2
    from /Users/daviss/.rbenv/versions/1.9.3-p484/bin/irb:12:in `<main>'
irb(main):003:0> require 'rubygems'

**Comment by scottyseus** [comment]
Does anyone know the difference between them?

**Comment by andrewhavens** [comment]
@scottyseus Always refer to RubyGems to find their GitHub repos:
- https://rubygems.org/gems/jira
- https://rubygems.org/gems/jira-ruby
