### ISSUE TITLE
Issue All error

### ISSUE THREAD

**Issue by bliaxiong** [sumoheavy/jira-ruby#69]
I'm getting an error when running 'client.Issue.all' when running code in the console. Any help is greatly appreciative. 

JRuby 1.7.10
Mac 

Trace:

jruby-1.7.10 :029 > client.Issue.all
NoMethodError: undefined method `split' for :expand:Symbol
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1598:in `capitalize'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1591:in `each_capitalized'
	from org/jruby/RubyHash.java:1338:in `each'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1590:in `each_capitalized'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:2081:in `write_header'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1933:in `exec'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1325:in `transport_request'
	from org/jruby/RubyKernel.java:1282:in `catch'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1324:in `transport_request'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1301:in `request'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1294:in `request'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:745:in `start'
	from /Users/bxiong/.rvm/rubies/jruby-1.7.10/lib/ruby/1.9/net/http.rb:1292:in `request'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/jira-ruby-0.1.8/lib/jira/http_client.rb:22:in `make_request'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/jira-ruby-0.1.8/lib/jira/request_client.rb:13:in `request'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/jira-ruby-0.1.8/lib/jira/client.rb:151:in `request'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/jira-ruby-0.1.8/lib/jira/client.rb:130:in `get'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/jira-ruby-0.1.8/lib/jira/resource/issue.rb:37:in `all'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/jira-ruby-0.1.8/lib/jira/base_factory.rb:33:in `all'
	from (irb):29:in `evaluate'
	from org/jruby/RubyKernel.java:1119:in `eval'
	from org/jruby/RubyKernel.java:1519:in `loop'
	from org/jruby/RubyKernel.java:1282:in `catch'
	from org/jruby/RubyKernel.java:1282:in `catch'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
	from /Users/bxiong/.rvm/gems/jruby-1.7.10@test/gems/railties-3.2.17/lib/rails/commands.rb:41:in `(root)'
	from org/jruby/RubyKernel.java:1083:in `require'
	from script/rails:6:in `(root)'jruby-1.7.10 :030 >

**Comment by jackdinh10** [comment]
I have found that I can do an empty JQL search in the issues to retrieve all the issues if the original way doesn't work.

`client.Issue.jql('')`
