### ISSUE TITLE
Init client via Basic Auth 

### ISSUE THREAD

**Issue by mkou** [sumoheavy/jira-ruby#75]
Hello , 
I need help for the simplest thing!
I am trying to init the client via basic Auth locally.
- I set up the Jira sdk
- I configured Jira Application Links with http://localhost:3000
- I added the gem to my gemfile

Then, when I try to run this simple script in my rails console

```
username = "admin"
password = "admin"
options = {
        :username => username,
        :password => password,
        :ssl_verify_mode    =>OpenSSL::SSL::VERIFY_NONE ,
        :auth_type          => :basic
}
client = JIRA::Client.new(options)
projects = client.Project.all
```

I got the error 

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
```

What did I do wrong ? 

EDIT: Found my mistake I did not need ssl in this case
Thanks

**Comment by vgr787878** [comment]
I have been facing same issue .How did you resolve this issue can you please help me in resolving this issue

**Comment by srinivasplt** [comment]
options = {:username => username, :password => password, :site     => 'http://localhost:2990/',  :context_path => '/jira', :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE, :use_ssl => false, :auth_type => :basic}

adding :use_ssl => false should bypass https connection.

**Comment by dideler** [comment]
Correct me if I'm wrong, but is there no way to use SSL when using basic authentication with this gem?

**Comment by pruan-rht** [comment]
The following works for me.
`options = {
            :username => ENV["JIRA_USER"],
            :password => ENV["JIRA_PASSWORD"],
            :site     => 'https://<your_site_url>/',
            :context_path => '',
            :auth_type => :basic,
            :ssl_verify_mode    =>OpenSSL::SSL::VERIFY_NONE ,
            :read_timeout => 120
          }

client = JIRA::Client.new(options)
`
