### ISSUE TITLE
Delete does not work on resources

### ISSUE THREAD

**Issue by herrphon** [sumoheavy/jira-ruby#80]
Hi,
I want to delete a resource which doesn't seem to work for me:

```
new_issue = client.Issue.build()
new_issue.save({"fields"=>{"summary"=>"test 123","project"=>{"key"=>"JIRA"}, :issuetype => {:name => 'Bug'}}})
new_issue.delete
```

or 

```
issue = client.Issue.find('JIRA-123')
issue.comments.last.delete
```

or others (e.g. version) 
will always result in:

```
/lib/ruby/gems/1.9.1/gems/jira-ruby-0.1.10/lib/jira/request_client.rb:14:in `request': Bad Request (JIRA::HTTPError)
    from /lib/ruby/gems/1.9.1/gems/jira-ruby-0.1.10/lib/jira/client.rb:155:in `request'
    from /lib/ruby/gems/1.9.1/gems/jira-ruby-0.1.10/lib/jira/client.rb:130:in `delete'
    from /lib/ruby/gems/1.9.1/gems/jira-ruby-0.1.10/lib/jira/base.rb:405:in `delete'
...
```

I'm running jira-ruby against a Jira version 6.1.5 and the same user can do deletes via http REST calls.

Thanks in advance.

**Comment by cemeyer2** [comment]
For posterity in case anyone else ends up here via google, I ran into this same exact bug but due to a slightly different reason. 

I used the following options:

```
jira_options = {
    :username => 'USERNAME',
    :password => 'PASSWORD',
    :site => 'https://myjira.example.com:443',
    :context_path => '',
    :auth_type => :basic
}
```

The `#url` method in `JIRA::Base` does some naïve string replacement which does not account for the trailing port number on the url, even though it is completely valid. Removing the `:443` from my url was the workaround. I would request that @bobbrodie reopen this issue so that we can track a fix.

**Comment by bobbrodie** [comment]
Great catch @cemeyer2, thanks for the detail -- reopened!

**Comment by SimonMiaou** [comment]
Is it stil the case? I think I always see full URLs
Also the code evolved since. I'm wondering if this issue is still useful.
The issue of @cemeyer2 seems to be the reason of the code I removed in #243

**Comment by seawolf** [comment]
> Is it still the case? I think I always see full URLs
> Also the code evolved since. I'm wondering if this issue is still useful.

I'm seeing this in a new project using the `ruby-jira` v1.7.1 and Jira Cloud. I'll see if it's fixed in the latest gem `v2.0.0`.

I can fetch issues using hte REST API but can't use `Issue#delete` -- I have client.delete('.../issues/12345) !

I'll see if it's fixed in the latest gem `v2.0.0`.

**Comment by x-yuri** [comment]
@bobbrodie @SimonMiaou Could you at least remove the trailing slashes from the README, and add a warning along the lines of "Do not add a trailing slash..."?

**Comment by SimonMiaou** [comment]
Hi @x-yuri ,
Thank you for your feedback, we'd be happy to receive a pull request from you with those changes!

**Comment by x-yuri** [comment]
@SimonMiaou See #359 please. And it probably makes sense to bump the version.
