### ISSUE TITLE
Create Project example

### ISSUE THREAD

**Issue by fertobar** [sumoheavy/jira-ruby#87]
Hi,
I was trying the gem and works very well for me. I could Find Project, create Issues, etc.

The question is about create a new Project using the gem. It's supported by the gem?

There is a working example for try for create Projects? 
I was trying with different attributes, but I'm getting false in the save.
 May be could be nice to show the error message in case some issue in save in case the api return that information.
thanks!

**Comment by yuri-karpovich** [comment]
And where is an answer?

**Comment by mtrepanier** [comment]
Doc for JIRA Rest API is here.
https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/?_ga=2.146130423.2104971424.1518189078-1321557285.1511468398#api/2/project

The fun part or a Restful API is that all ressource act the same.

So if you look at create, you can see the field needed.  Of course different JIRA setup can hanve different mandatory fields.

https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/?_ga=2.146130423.2104971424.1518189078-1321557285.1511468398#api/2/project-createProject

Based on the basic instance, the required fields are
```
{
  "key": "EX",
  "name": "Example",
  "projectTypeKey": "business",
  "lead": "username"
}
```

Based on that fact, the query in `Jira-Ruby` to create a project would be.
```
project = client.Project.build
project.save({"fields"=>{"key" => "EX", "name" => "Example", "projectTypeKey" => "business", "lead" => "username"}})
project.fetch
```
