### ISSUE TITLE
Saving/deleting a comment doesn't work with Jira 6

### ISSUE THREAD

**Issue by nthx** [sumoheavy/jira-ruby#89]
I can confirm saving/deleting a comment doesn't work in 0.1.11

The reason is, during a request, url path has the first character "/" being removed.

See working "GET issues" vs not working "PUT comment".
I traced it by putting custom logs inside lib/jira/http_client.rb#make_request

    get
    /rest/api/2/issue/MWS-303
    {"Accept"=>"application/json"}

vs not working, and resulting in: 
lib/jira/request_client.rb:14:in `request': Bad Request (JIRA::HTTPError)

    :put
    "rest/api/2/issue/30259/comment/41171"
    {"Content-Type"=>"application/json"}
    "{\"body\":\"cccc\"}"

**Comment by endymion** [comment]
Thank you for your help.  That finally worked after hours of hassle.  I still can't update the fields on an existing issue.

This Ruby gem is an unreliable piece of undocumented garbage.  Even if I can get this working I don't know if I can justify putting this code into production and cursing some future maintainer with the hassle of trying to figure out how to make this gem work.  If anybody has found better ways of using the JIRA API from Ruby then please let me know.
