### ISSUE TITLE
JQL with expanded changelog

### ISSUE THREAD

**Issue by blainesch** [sumoheavy/jira-ruby#93]
You can use the issue finder to get the changelog but not sql. This can cause an excess of queries. Is there a way around this? I can't seem to find a way to pass in `expand=changelog` into the jql function just: `jql`, `fields`, `startAt`, and `maxResults`. [Source](https://github.com/sumoheavy/jira-ruby/blob/master/lib/jira/resource/issue.rb#L50-L52)
~~~ ruby
client.Issue.jql('project = VIT AND sprint in openSprints()').each do |issue|
  issue = client.Issue.find(issue.key, {expand: 'changelog'})
end
~~~

**Comment by dillonkearns** [comment]
@blainesch not sure if this is still relevant to you, but it's easy enough to mokey patch this in:

```ruby
module JIRA
  module Resource
    class Issue < JIRA::Base


      def self.jql(client, jql, options = {fields: nil, start_at: nil, max_results: nil})
        url = client.options[:rest_base_path] + "/search?jql=" + CGI.escape(jql)

        url << "&fields=#{options[:fields].map{ |value| CGI.escape(value.to_s) }.join(',')}" if options[:fields]
        url << "&startAt=#{CGI.escape(options[:start_at].to_s)}" if options[:start_at]
        url << "&maxResults=#{CGI.escape(options[:max_results].to_s)}" if options[:max_results]
        url << "&expand=#{CGI.escape(options[:expand].to_s)}" if options[:expand]

        response = client.get(url)
        json = parse_json(response.body)
        json['issues'].map do |issue|
          client.Issue.build(issue)
        end
      end
    end
  end
end
```

And it would be quite simple to modify the code itself. It might be nice if the url options were generalized to accept any option passed in instead of hard-coding each possibility (but I'm sure there are some trade-offs and corner cases there).

**Comment by blainesch** [comment]
@dillonkearns it's not as relevant anymore, but I'm sure this would be a nice to have in the project. Maybe you should open up a pr?

**Comment by dillonkearns** [comment]
Done!
