### ISSUE TITLE
Upload attachment

### ISSUE THREAD

**Issue by garciaf** [sumoheavy/jira-ruby#94]
Hello guys, is there a way to upload an attachment using your gem?
Thanks for your time

**Comment by goraxe** [comment]
I managed it with the following monkey patch, if I find time I will try and come up with a pull request 

 module JIRA
      module Resource
          class Attachment < JIRA::Base
              belongs_to :issue
              def self.endpoint_name
                  return "attachments"
              end 
              def save!(attrs)
                  http_method = new_record? ? :post : :put
                  headers = { 
                      "X-Atlassian-Token" => "nocheck"
                  }   
                  request = Net::HTTP::Post::Multipart.new url,
                      { "file" => UploadIO.new(File.new(attrs['file']), "application/binary", attrs['file']) },
                      headers
                  request_client = client.request_client
                  options = client.request_client.options
  
                  request.basic_auth(options[:username], options[:password])
                  response = request_client.basic_auth_http_conn.request(request) 
  
                  set_attrs(attrs, false)
                  unless response.body.nil? or response.body.length < 2 
                      json = self.class.parse_json(response.body)
                      attachment = json[0]
                      set_attrs(attachment)
                  end 
  
                  @expanded = false
                  true
              end 
          end 
      end 
  end

**Comment by dfyx** [comment]
Works great for me

**Comment by dingokiller** [comment]
Could somehow help me understand where I should put this Monkey Patch -- and how to invoke it. 

I imagine something like

    attachment= issue.attachments.build
    attachments.save!(:body => "Path/To/File")

**Comment by dfyx** [comment]
Just put it in a file somewhere in your load path (like `lib/ext/jira/attachment.rb`) and require it.

As for using it:

```
# Assuming @client is your JIRA client instance
attachment = JIRA::Resource::Attachment.new @client, issue: issue
attachment.save! file: 'path/to/file.txt'
```

(Or something similar. I'm at home right now so I can't look at the code I wrote at work)

**Comment by dingokiller** [comment]
Thanks for the quick response - looks like I am close. I had to add the multipart gem on top to resolve an uninitialized constant error, and I am now trying to work through 

'No implicit conversion of nil to String', coming from the "file" => UploadIO.new, line.

        request = Net::HTTP::Post::Multipart.new url, 
                  {
                      "file" => UploadIO.new(File.new(attrs['file']), 
                                             "application/binary", attrs['file']) }, 
                                                 headers

**Comment by dfyx** [comment]
Ah, right. It has to be `attachment.save! 'file' => 'path/to/file.txt'` with a string instead of a symbol as the key.

**Comment by omehegan** [comment]
I would love to see this integrated as a core feature. Thanks!

**Comment by omehegan** [comment]
@dingokiller wrote "I had to add the multipart gem on top to resolve an uninitialized constant error..." This threw me off when I got the same error. The correct gem needed is 'multipart-post,' not 'multipart.'

**Comment by dingokiller** [comment]
@omehegan Apologies - i was using multipart-post the whole time, I incorrectly referenced it in my update on GitHub. Indeed, the require is mandatory as well, with both of those steps I was able to get this code working in my project.

**Comment by sam2themax** [comment]
Was this closed because the gem supports this or for some other reason? Is this related to [PR #28](https://github.com/sumoheavy/jira-ruby/pull/28) ?

**Comment by bobbrodie** [comment]
@sam2themax this was closed due to inactivity as part of a cleanup script. If it's still of interest for most users, let's open a new issue.

**Comment by sam2themax** [comment]
@bobbrodie thanks for the explanation!

I was reviewing code on an internal work project that was employing the above monkey patch and looking for a way to do things without patching.  Further reflection by my co-worker revealed that we don't need it for now.

**Comment by z4nn** [comment]
This does not seem to work if using OAuth instead of basic authentication - any suggestion?
