### ISSUE TITLE
Linking issues

### ISSUE THREAD

**Issue by cristim** [sumoheavy/jira-ruby#95]
Hello

Is there a way to create link relationships between issues? I need to do it both within the same JIRA instance and across multiple instances.

Thanks!

**Comment by frackietv** [comment]
I've run into the same need and could not find a fix, so had to come up with it myself.

Few months too late, but here it is:

    module JIRA
      module Resource
        class IssueLinktypeFactory < JIRA::BaseFactory ; end
        class IssueLinktype < JIRA::Base ; end
        class IssueLinkFactory < JIRA::BaseFactory ; end

        class IssueLink < JIRA::Base
          has_one :type, :class => JIRA::Resource::IssueLinktype
          has_one :inwardIssue, :class => JIRA::Resource::Issue
          has_one :outwardIssue, :class => JIRA::Resource::Issue

          def self.endpoint_name
            'issueLink'
          end
        end
      end

      class Client
        def IssueLink
          JIRA::Resource::IssueLinkFactory.new(self)
        end
        def IssueLinktype
          JIRA::Resource::IssueLinktypeFactory.new(self)
        end
      end
    end

And to link the two issues:

    link = client.IssueLink.build
    link.save({'type'=>{'name'=>' Relates'},'inwardIssue'=>{'key'=>'EXAMPLE-1'},'outwardIssue'=>{'key'=>'EXAMPLE-2'}})

For some reason, I needed the space in the name, before 'Relates': `' Relates'`.

**Comment by dfyx** [comment]
@frackietv Pretty useful. Can you turn this into a pull request?
